// Generated by gencpp from file robot_scripts/LidarAggregationRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SCRIPTS_MESSAGE_LIDARAGGREGATIONREQUEST_H
#define ROBOT_SCRIPTS_MESSAGE_LIDARAGGREGATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/LaserScan.h>

namespace robot_scripts
{
template <class ContainerAllocator>
struct LidarAggregationRequest_
{
  typedef LidarAggregationRequest_<ContainerAllocator> Type;

  LidarAggregationRequest_()
    : Scans()  {
    }
  LidarAggregationRequest_(const ContainerAllocator& _alloc)
    : Scans(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::LaserScan_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::LaserScan_<ContainerAllocator> >::other >  _Scans_type;
  _Scans_type Scans;





  typedef boost::shared_ptr< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LidarAggregationRequest_

typedef ::robot_scripts::LidarAggregationRequest_<std::allocator<void> > LidarAggregationRequest;

typedef boost::shared_ptr< ::robot_scripts::LidarAggregationRequest > LidarAggregationRequestPtr;
typedef boost::shared_ptr< ::robot_scripts::LidarAggregationRequest const> LidarAggregationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_scripts::LidarAggregationRequest_<ContainerAllocator1> & lhs, const ::robot_scripts::LidarAggregationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Scans == rhs.Scans;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_scripts::LidarAggregationRequest_<ContainerAllocator1> & lhs, const ::robot_scripts::LidarAggregationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_scripts

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78bb0db4a27d3a869e1fac3f4dfb4494";
  }

  static const char* value(const ::robot_scripts::LidarAggregationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78bb0db4a27d3a86ULL;
  static const uint64_t static_value2 = 0x9e1fac3f4dfb4494ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scripts/LidarAggregationRequest";
  }

  static const char* value(const ::robot_scripts::LidarAggregationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/LaserScan[] Scans\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/LaserScan\n"
"# Single scan from a planar laser range-finder\n"
"#\n"
"# If you have another ranging device with different behavior (e.g. a sonar\n"
"# array), please find or create a different message, since applications\n"
"# will make fairly laser-specific assumptions about this data\n"
"\n"
"Header header            # timestamp in the header is the acquisition time of \n"
"                         # the first ray in the scan.\n"
"                         #\n"
"                         # in frame frame_id, angles are measured around \n"
"                         # the positive Z axis (counterclockwise, if Z is up)\n"
"                         # with zero angle being forward along the x axis\n"
"                         \n"
"float32 angle_min        # start angle of the scan [rad]\n"
"float32 angle_max        # end angle of the scan [rad]\n"
"float32 angle_increment  # angular distance between measurements [rad]\n"
"\n"
"float32 time_increment   # time between measurements [seconds] - if your scanner\n"
"                         # is moving, this will be used in interpolating position\n"
"                         # of 3d points\n"
"float32 scan_time        # time between scans [seconds]\n"
"\n"
"float32 range_min        # minimum range value [m]\n"
"float32 range_max        # maximum range value [m]\n"
"\n"
"float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n"
"float32[] intensities    # intensity data [device-specific units].  If your\n"
"                         # device does not provide intensities, please leave\n"
"                         # the array empty.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_scripts::LidarAggregationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Scans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarAggregationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_scripts::LidarAggregationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_scripts::LidarAggregationRequest_<ContainerAllocator>& v)
  {
    s << indent << "Scans[]" << std::endl;
    for (size_t i = 0; i < v.Scans.size(); ++i)
    {
      s << indent << "  Scans[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "    ", v.Scans[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SCRIPTS_MESSAGE_LIDARAGGREGATIONREQUEST_H
