// Generated by gencpp from file robot_scripts/lidar_scanResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_SCRIPTS_MESSAGE_LIDAR_SCANRESPONSE_H
#define ROBOT_SCRIPTS_MESSAGE_LIDAR_SCANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_scripts
{
template <class ContainerAllocator>
struct lidar_scanResponse_
{
  typedef lidar_scanResponse_<ContainerAllocator> Type;

  lidar_scanResponse_()
    : done(false)  {
    }
  lidar_scanResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct lidar_scanResponse_

typedef ::robot_scripts::lidar_scanResponse_<std::allocator<void> > lidar_scanResponse;

typedef boost::shared_ptr< ::robot_scripts::lidar_scanResponse > lidar_scanResponsePtr;
typedef boost::shared_ptr< ::robot_scripts::lidar_scanResponse const> lidar_scanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_scripts::lidar_scanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_scripts::lidar_scanResponse_<ContainerAllocator1> & lhs, const ::robot_scripts::lidar_scanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_scripts::lidar_scanResponse_<ContainerAllocator1> & lhs, const ::robot_scripts::lidar_scanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_scripts

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::robot_scripts::lidar_scanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scripts/lidar_scanResponse";
  }

  static const char* value(const ::robot_scripts::lidar_scanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n"
"\n"
;
  }

  static const char* value(const ::robot_scripts::lidar_scanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lidar_scanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_scripts::lidar_scanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_scripts::lidar_scanResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SCRIPTS_MESSAGE_LIDAR_SCANRESPONSE_H
