(cl:in-package robot_navigation-msg)
(cl:export '(STAMP-VAL
          STAMP
          FRAME_ID-VAL
          FRAME_ID
          DIRECTION-VAL
          DIRECTION
          CEILING_HEIGHT_NEAR-VAL
          CEILING_HEIGHT_NEAR
          CEILING_HEIGHT_MID-VAL
          CEILING_HEIGHT_MID
          CEILING_HEIGHT_FAR-VAL
          CEILING_HEIGHT_FAR
          WALL_DISTANCE_NEAR-VAL
          WALL_DISTANCE_NEAR
          WALL_DISTANCE_MID-VAL
          WALL_DISTANCE_MID
          WALL_DISTANCE_FAR-VAL
          WALL_DISTANCE_FAR
          FLOOR_DISTANCE-VAL
          FLOOR_DISTANCE
          FLOOR_SLOPE-VAL
          FLOOR_SLOPE
          FLOOR_TYPE-VAL
          FLOOR_TYPE
          WALL_TYPE-VAL
          WALL_TYPE
          CEILING_TYPE-VAL
          CEILING_TYPE
))