(cl:in-package robot_navigation-msg)
(cl:export '(STAMP-VAL
          STAMP
          FRAME_ID-VAL
          FRAME_ID
          LAST_CMD-VAL
          LAST_CMD
          FLOOR-VAL
          FLOOR
          WALL-VAL
          WALL
          CEILING-VAL
          CEILING
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          POSITION_ROBOT-VAL
          POSITION_ROBOT
          TYPE_ENVIRONMENT-VAL
          TYPE_ENVIRONMENT
          ACCESSIBILITY-VAL
          ACCESSIBILITY
))