// Generated by gencpp from file robot_navigation/cmd_vel_pub.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_CMD_VEL_PUB_H
#define ROBOT_NAVIGATION_MESSAGE_CMD_VEL_PUB_H

#include <ros/service_traits.h>


#include <robot_navigation/cmd_vel_pubRequest.h>
#include <robot_navigation/cmd_vel_pubResponse.h>


namespace robot_navigation
{

struct cmd_vel_pub
{

typedef cmd_vel_pubRequest Request;
typedef cmd_vel_pubResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd_vel_pub
} // namespace robot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_navigation::cmd_vel_pub > {
  static const char* value()
  {
    return "5e16a6b946eb627ffe9d5c82c7296a8e";
  }

  static const char* value(const ::robot_navigation::cmd_vel_pub&) { return value(); }
};

template<>
struct DataType< ::robot_navigation::cmd_vel_pub > {
  static const char* value()
  {
    return "robot_navigation/cmd_vel_pub";
  }

  static const char* value(const ::robot_navigation::cmd_vel_pub&) { return value(); }
};


// service_traits::MD5Sum< ::robot_navigation::cmd_vel_pubRequest> should match
// service_traits::MD5Sum< ::robot_navigation::cmd_vel_pub >
template<>
struct MD5Sum< ::robot_navigation::cmd_vel_pubRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::cmd_vel_pub >::value();
  }
  static const char* value(const ::robot_navigation::cmd_vel_pubRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::cmd_vel_pubRequest> should match
// service_traits::DataType< ::robot_navigation::cmd_vel_pub >
template<>
struct DataType< ::robot_navigation::cmd_vel_pubRequest>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::cmd_vel_pub >::value();
  }
  static const char* value(const ::robot_navigation::cmd_vel_pubRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_navigation::cmd_vel_pubResponse> should match
// service_traits::MD5Sum< ::robot_navigation::cmd_vel_pub >
template<>
struct MD5Sum< ::robot_navigation::cmd_vel_pubResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::cmd_vel_pub >::value();
  }
  static const char* value(const ::robot_navigation::cmd_vel_pubResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::cmd_vel_pubResponse> should match
// service_traits::DataType< ::robot_navigation::cmd_vel_pub >
template<>
struct DataType< ::robot_navigation::cmd_vel_pubResponse>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::cmd_vel_pub >::value();
  }
  static const char* value(const ::robot_navigation::cmd_vel_pubResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_CMD_VEL_PUB_H
