// Generated by gencpp from file robot_navigation/environment_processRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_ENVIRONMENT_PROCESSREQUEST_H
#define ROBOT_NAVIGATION_MESSAGE_ENVIRONMENT_PROCESSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_navigation
{
template <class ContainerAllocator>
struct environment_processRequest_
{
  typedef environment_processRequest_<ContainerAllocator> Type;

  environment_processRequest_()
    {
    }
  environment_processRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robot_navigation::environment_processRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_navigation::environment_processRequest_<ContainerAllocator> const> ConstPtr;

}; // struct environment_processRequest_

typedef ::robot_navigation::environment_processRequest_<std::allocator<void> > environment_processRequest;

typedef boost::shared_ptr< ::robot_navigation::environment_processRequest > environment_processRequestPtr;
typedef boost::shared_ptr< ::robot_navigation::environment_processRequest const> environment_processRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_navigation::environment_processRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_navigation::environment_processRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robot_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::environment_processRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::environment_processRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::environment_processRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::environment_processRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::environment_processRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::environment_processRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_navigation::environment_processRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robot_navigation::environment_processRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_navigation::environment_processRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_navigation/environment_processRequest";
  }

  static const char* value(const ::robot_navigation::environment_processRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_navigation::environment_processRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::robot_navigation::environment_processRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_navigation::environment_processRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct environment_processRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_navigation::environment_processRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robot_navigation::environment_processRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_ENVIRONMENT_PROCESSREQUEST_H
