// Generated by gencpp from file robot_navigation/environment_process.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_ENVIRONMENT_PROCESS_H
#define ROBOT_NAVIGATION_MESSAGE_ENVIRONMENT_PROCESS_H

#include <ros/service_traits.h>


#include <robot_navigation/environment_processRequest.h>
#include <robot_navigation/environment_processResponse.h>


namespace robot_navigation
{

struct environment_process
{

typedef environment_processRequest Request;
typedef environment_processResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct environment_process
} // namespace robot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_navigation::environment_process > {
  static const char* value()
  {
    return "057db96ed4fd37f01b787776b6ce3971";
  }

  static const char* value(const ::robot_navigation::environment_process&) { return value(); }
};

template<>
struct DataType< ::robot_navigation::environment_process > {
  static const char* value()
  {
    return "robot_navigation/environment_process";
  }

  static const char* value(const ::robot_navigation::environment_process&) { return value(); }
};


// service_traits::MD5Sum< ::robot_navigation::environment_processRequest> should match
// service_traits::MD5Sum< ::robot_navigation::environment_process >
template<>
struct MD5Sum< ::robot_navigation::environment_processRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::environment_process >::value();
  }
  static const char* value(const ::robot_navigation::environment_processRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::environment_processRequest> should match
// service_traits::DataType< ::robot_navigation::environment_process >
template<>
struct DataType< ::robot_navigation::environment_processRequest>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::environment_process >::value();
  }
  static const char* value(const ::robot_navigation::environment_processRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_navigation::environment_processResponse> should match
// service_traits::MD5Sum< ::robot_navigation::environment_process >
template<>
struct MD5Sum< ::robot_navigation::environment_processResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::environment_process >::value();
  }
  static const char* value(const ::robot_navigation::environment_processResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::environment_processResponse> should match
// service_traits::DataType< ::robot_navigation::environment_process >
template<>
struct DataType< ::robot_navigation::environment_processResponse>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::environment_process >::value();
  }
  static const char* value(const ::robot_navigation::environment_processResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_ENVIRONMENT_PROCESS_H
