// Generated by gencpp from file robot_navigation/Joint_state_infoResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_JOINT_STATE_INFORESPONSE_H
#define ROBOT_NAVIGATION_MESSAGE_JOINT_STATE_INFORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_navigation
{
template <class ContainerAllocator>
struct Joint_state_infoResponse_
{
  typedef Joint_state_infoResponse_<ContainerAllocator> Type;

  Joint_state_infoResponse_()
    : resp_data(0.0)  {
    }
  Joint_state_infoResponse_(const ContainerAllocator& _alloc)
    : resp_data(0.0)  {
  (void)_alloc;
    }



   typedef double _resp_data_type;
  _resp_data_type resp_data;





  typedef boost::shared_ptr< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Joint_state_infoResponse_

typedef ::robot_navigation::Joint_state_infoResponse_<std::allocator<void> > Joint_state_infoResponse;

typedef boost::shared_ptr< ::robot_navigation::Joint_state_infoResponse > Joint_state_infoResponsePtr;
typedef boost::shared_ptr< ::robot_navigation::Joint_state_infoResponse const> Joint_state_infoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator1> & lhs, const ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.resp_data == rhs.resp_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator1> & lhs, const ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "741558e2f9de9b48acbf05de738eda9c";
  }

  static const char* value(const ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x741558e2f9de9b48ULL;
  static const uint64_t static_value2 = 0xacbf05de738eda9cULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_navigation/Joint_state_infoResponse";
  }

  static const char* value(const ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 resp_data\n"
"\n"
;
  }

  static const char* value(const ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resp_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joint_state_infoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_navigation::Joint_state_infoResponse_<ContainerAllocator>& v)
  {
    s << indent << "resp_data: ";
    Printer<double>::stream(s, indent + "  ", v.resp_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_JOINT_STATE_INFORESPONSE_H
