// Generated by gencpp from file robot_navigation/Joint_state_info.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_JOINT_STATE_INFO_H
#define ROBOT_NAVIGATION_MESSAGE_JOINT_STATE_INFO_H

#include <ros/service_traits.h>


#include <robot_navigation/Joint_state_infoRequest.h>
#include <robot_navigation/Joint_state_infoResponse.h>


namespace robot_navigation
{

struct Joint_state_info
{

typedef Joint_state_infoRequest Request;
typedef Joint_state_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Joint_state_info
} // namespace robot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_navigation::Joint_state_info > {
  static const char* value()
  {
    return "741558e2f9de9b48acbf05de738eda9c";
  }

  static const char* value(const ::robot_navigation::Joint_state_info&) { return value(); }
};

template<>
struct DataType< ::robot_navigation::Joint_state_info > {
  static const char* value()
  {
    return "robot_navigation/Joint_state_info";
  }

  static const char* value(const ::robot_navigation::Joint_state_info&) { return value(); }
};


// service_traits::MD5Sum< ::robot_navigation::Joint_state_infoRequest> should match
// service_traits::MD5Sum< ::robot_navigation::Joint_state_info >
template<>
struct MD5Sum< ::robot_navigation::Joint_state_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::Joint_state_info >::value();
  }
  static const char* value(const ::robot_navigation::Joint_state_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::Joint_state_infoRequest> should match
// service_traits::DataType< ::robot_navigation::Joint_state_info >
template<>
struct DataType< ::robot_navigation::Joint_state_infoRequest>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::Joint_state_info >::value();
  }
  static const char* value(const ::robot_navigation::Joint_state_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_navigation::Joint_state_infoResponse> should match
// service_traits::MD5Sum< ::robot_navigation::Joint_state_info >
template<>
struct MD5Sum< ::robot_navigation::Joint_state_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_navigation::Joint_state_info >::value();
  }
  static const char* value(const ::robot_navigation::Joint_state_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_navigation::Joint_state_infoResponse> should match
// service_traits::DataType< ::robot_navigation::Joint_state_info >
template<>
struct DataType< ::robot_navigation::Joint_state_infoResponse>
{
  static const char* value()
  {
    return DataType< ::robot_navigation::Joint_state_info >::value();
  }
  static const char* value(const ::robot_navigation::Joint_state_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_JOINT_STATE_INFO_H
