// Generated by gencpp from file robot_navigation/Joint_state_infoRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_JOINT_STATE_INFOREQUEST_H
#define ROBOT_NAVIGATION_MESSAGE_JOINT_STATE_INFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_navigation
{
template <class ContainerAllocator>
struct Joint_state_infoRequest_
{
  typedef Joint_state_infoRequest_<ContainerAllocator> Type;

  Joint_state_infoRequest_()
    {
    }
  Joint_state_infoRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Joint_state_infoRequest_

typedef ::robot_navigation::Joint_state_infoRequest_<std::allocator<void> > Joint_state_infoRequest;

typedef boost::shared_ptr< ::robot_navigation::Joint_state_infoRequest > Joint_state_infoRequestPtr;
typedef boost::shared_ptr< ::robot_navigation::Joint_state_infoRequest const> Joint_state_infoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robot_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_navigation/Joint_state_infoRequest";
  }

  static const char* value(const ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joint_state_infoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robot_navigation::Joint_state_infoRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_JOINT_STATE_INFOREQUEST_H
